[project]
name = "omop-etl"
version = "0.1.0"
description = "ETL for PRIME ROSE to OMOP CDM"
authors = [{ name = "Gabriel B. Stav" }]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
  "python-dotenv>=1,<2",
  "openpyxl>=3.1,<4",
  "pandas>=2.2,<3",
  "pydantic>=2.10,<3",
  "ruff>=0.9,<0.10",
  "mypy>=1.14,<2",
  "ns>=0.1,<0.2",
  "polars>=1.22,<2",
  "typer>=0.16.0",
  "json5>=0.12.0",
  "fastexcel>=0.14.0",
  "deprecated>=1.2.18",
]

[project.scripts]
omop-harmonize = "omop_etl.cli.harmonize:main"
omop-preprocess = "omop_etl.cli.preprocess:main"

[dependency-groups]
dev = ["pytest>=7,<9", "pre-commit>=3,<4"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/omop_etl"]
package-data = { "omop_etl" = ["resources/*.json"] }

[tool.ruff]
line-length = 250
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E203", "F401", "F811", "F821", "F841", "E501"]

[tool.pytest.ini_options]
testpaths = ["tests"]
